project_id = "edutester"

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)"

[functions.razorpay-create-order]
verify_jwt = true

[functions.razorpay-verify]
verify_jwt = true
